
services:
    db:
        image: postgres:16.0
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
    app:
        build: ./
        restart: always
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            DATABASE_URL: "postgresql://postgres:password@db:5432/db"
